### PR TITLE
docs: Translate all headings into Chinese

### PR DESCRIPTION
**Pull request by WhaleChen**
Make documentations formal and friendly to Chinese users.

### CODE REVIEW

**Comment by WhaleChen** [comment]
Sorry, I made a mistake and missed client.py #139, so I closed it. Now all the things go right. Pls check it.

**Comment by littlecodersh** [comment]
@WhaleChen Thank you for your contribution! It has been merged into itchat.
Actually there's still a mistake about client.py, which I've rewritten to make it right.
It doesn't matter to me, but you may want to figure out why it happened.
And thank you again.

**Comment by WhaleChen** [comment]
@littlecodersh 3x so much! I have some misunderstanding with git tool, now you have made me right. Many thanks, hope itchat will do better! 
screen shot 2016-11-03 at 2 57 28 pm

**Comment by tempdban** [comment]
@WhaleChen @littlecodersh 我可以单独开pr问问英语怎么学么...

**Comment by littlecodersh** [comment]
@tempdban 我这里就是九年义务教育（摊手）

**Comment by WhaleChen** [comment]
@tempdban 我们用中文可以的，只是我的命令行支持写入中文有些问题。享受就好！

**Comment by tempdban** [comment]
@littlecodersh @WhaleChen 不是要用中文的意思。。。我是说你们某些词用的很精妙。。。就是好奇你们平时都看什么文章啊

**Pull request merged**
